# Generated by Django 4.2.6 on 2023-10-30 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_services', models.CharField(max_length=200, unique=True, verbose_name='Название услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена услуги')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Услугу',
                'verbose_name_plural': 'Услуги',
                'ordering': ['-time_create', 'name_services'],
            },
        ),
        migrations.CreateModel(
            name='WashOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=255, unique=True, verbose_name='Название машины')),
                ('car_number', models.CharField(max_length=255, unique=True, verbose_name='Номер авто')),
                ('car_owner_name', models.CharField(max_length=255, unique=True, verbose_name='Имя владельца авто')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employees', verbose_name='Автомойщик')),
                ('type_of_car_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.services', verbose_name='Вид мойки')),
            ],
            options={
                'verbose_name': 'Заказ на мойку',
                'verbose_name_plural': 'Заказы на мойку',
                'ordering': ['-time_create', 'car_name'],
            },
        ),
    ]
