# Generated by Django 4.2.6 on 2023-10-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washorders',
            name='car_name',
            field=models.CharField(max_length=255, verbose_name='Название машины'),
        ),
        migrations.AlterField(
            model_name='washorders',
            name='car_number',
            field=models.CharField(max_length=255, verbose_name='Номер авто'),
        ),
        migrations.AlterField(
            model_name='washorders',
            name='car_owner_name',
            field=models.CharField(max_length=255, verbose_name='Имя владельца авто'),
        ),
    ]
