# Generated by Django 4.2.6 on 2023-10-30 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_positions', models.CharField(max_length=100, unique=True, verbose_name='Название должности')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['-time_update', 'name_positions'],
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_employees', models.CharField(max_length=255, unique=True, verbose_name='ФИО')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=10, verbose_name='Пол')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('address', models.TextField(blank=True, verbose_name='Адрес проживания')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Дата приёма на работу')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оклад')),
                ('pinfl', models.CharField(max_length=14, verbose_name='ПИНФЛ')),
                ('passport_number', models.CharField(max_length=50, verbose_name='Серия и № паспорта')),
                ('passport_issued_by', models.CharField(max_length=200, verbose_name='Кем выдан паспорт')),
                ('passport_issued_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта')),
                ('fired', models.BooleanField(verbose_name='Статус увольнения')),
                ('date_of_termination', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('photo', models.ImageField(blank=True, default='employees_photos/default.png', null=True, upload_to='employees_photos/', verbose_name='Фото')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.positions', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['-time_create', 'name_employees', 'fired'],
            },
        ),
    ]
